### ISSUE TITLE
ArcSegment IsLargeArc

### ISSUE THREAD

**Issue by robbym** [GuOrg/Gu.Wpf.Geometry#29]
Thanks for your recent work on ArcSegment! Ran into a little issue.

The following XAML:
```xaml
            <geometry:GradientPath GradientMode="Parallel" StrokeThickness="10" Tolerance="0.01">
                <geometry:GradientPath.Data>
                    <PathGeometry>
                        <PathFigure StartPoint="0,0">
                            <ArcSegment Point="140,0" Size="100,100" IsLargeArc="False" SweepDirection="Clockwise"/>
                        </PathFigure>
                    </PathGeometry>
                </geometry:GradientPath.Data>
                <geometry:GradientPath.GradientStops>
                    <GradientStop Offset="0" Color="Red" />
                    <GradientStop Offset="0.5" Color="Yellow" />
                    <GradientStop Offset="1" Color="Orange" />
                </geometry:GradientPath.GradientStops>
            </geometry:GradientPath>
```
Produces:
![2019-02-26 13_46_29-pid rate tester - microsoft visual studio](https://user-images.githubusercontent.com/7476885/53445115-0ff05b80-39cd-11e9-9be1-6b51a812424f.png)

Which seems correct.
However, setting `IsLargeArc` to `True` produces the following:
![2019-02-26 13_47_01-pid rate tester - microsoft visual studio](https://user-images.githubusercontent.com/7476885/53445157-2a2a3980-39cd-11e9-8727-a29f9e706c9c.png)

It seems like the ArcSegment gradient code is not taking into account `IsLargeArc`?

**Comment by JohanLarsson** [comment]
Nice issue, thanks for reporting!
I'll have a look when I find time unless you want to have a go?

**Comment by robbym** [comment]
I'll give it a try!

**Comment by JohanLarsson** [comment]
Note that the UI-tests on azrure-devops are failing for some reason.
So that you don't lose time thinking it was something you broke.

**Comment by JohanLarsson** [comment]
Released a new package: https://www.nuget.org/packages/Gu.Wpf.Geometry/2.2.3
Nuget needs a couple of minutes to index it before you can update.
